### PR TITLE
CSC notebook

### PR DESCRIPTION
**Pull request by ake123**
CSC notebook slides

### CODE REVIEW

**Review by antagomir — APPROVED** [review]

**Comment by antagomir** [comment]
@ake123 thanks! could you also add link to those slide here in this TOC?
https://microbiome.github.io/outreach/

**Comment by TuomasBorman** [comment]
Looks nice!

We have this website, where rendered slides are available: https://microbiome.github.io/outreach/

I did not notice before, but there is "Getting started" slides. Instead of creating new slides, you could extend this slide set. Couple of notes:

1. Remove (GB) from titles
2. From [course website](https://microbiome.github.io/course_2023_oulu/start.html) --> From OMA training chapter (or something)
3. Teaching environment (GB) seems to have only notes for teacher. --> integrate relevant info to your slides (for example lifetime of session)

**Comment by TuomasBorman** [comment]
> @ake123 thanks! could you also add link to those slide here in this TOC? https://microbiome.github.io/outreach/

There is already slides for "getting started" --> it would be better to integrate these new slides to it

**Comment by TuomasBorman** [comment]
This one https://microbiome.github.io/outreach/starting.html#/title-slide

**Comment by antagomir** [comment]
Yes, good idea. 

Rename it to "Learning environment" and move it form "Microbiome analysis" section to "Quarto" section and rename "Quarto" section also to "Learning environment"

**Comment by ake123** [comment]
Yes sure I will make the changes

**Pull request merged**
